# Generated by Django 3.0.10 on 2020-09-27 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0021_cpuproductclass'),
        ('catalogue', '0021_cpu'),
    ]

    operations = [
    ]
